alter table public.erhebungen
  add column if not exists lyse_ki_vor_oak boolean not null default false,
  add column if not exists lyse_ki_vor_zeitfenster boolean not null default false,
  add column if not exists lyse_ki_vor_blutung_cct boolean not null default false,
  add column if not exists lyse_ki_vor_op_trauma boolean not null default false,
  add column if not exists lyse_ki_vor_reanimation boolean not null default false,
  add column if not exists lyse_ki_vor_icb boolean not null default false,
  add column if not exists lyse_ki_vor_blutungsneigung boolean not null default false,
  add column if not exists lyse_ki_vor_schwere_blutung boolean not null default false,
  add column if not exists lyse_ki_vor_endokarditis boolean not null default false,
  add column if not exists lyse_ki_vor_sonstige boolean not null default false,
  add column if not exists lyse_ki_vor_sonstige_text text,
  add column if not exists lyse_ki_nach_oak boolean not null default false,
  add column if not exists lyse_ki_nach_zeitfenster boolean not null default false,
  add column if not exists lyse_ki_nach_blutung_cct boolean not null default false,
  add column if not exists lyse_ki_nach_op_trauma boolean not null default false,
  add column if not exists lyse_ki_nach_reanimation boolean not null default false,
  add column if not exists lyse_ki_nach_icb boolean not null default false,
  add column if not exists lyse_ki_nach_blutungsneigung boolean not null default false,
  add column if not exists lyse_ki_nach_schwere_blutung boolean not null default false,
  add column if not exists lyse_ki_nach_endokarditis boolean not null default false,
  add column if not exists lyse_ki_nach_sonstige boolean not null default false,
  add column if not exists lyse_ki_nach_sonstige_text text;
